const DataPage = [
  {
      id: 1,
      TeamName: "Copywriting",
      // Roles: "Content Writers, Copywriters, Technical Writers",
      Names: ["Aurora Basnet", "Marie Clardy"],

  },
  {
    id: 1,
    TeamName: "Cybersecurity and Data Privacy",
    // Roles: "Cybersecurity,Privacy,Data Privacy ",
    Names: ["Somya Narain", "Viswajit Srinivasan"],
  },
  {
    id: 2,
    TeamName: "Data Science ",
    // Roles: "Data Analysts,Data Scientists,Data Engineers ",
    Names: [
      "Ayushi Malaviya",
      "Ebunoluwa Adejayan",
      "Onidajo Wale-Olayitan",
      "Rishitha Golla",
    ],
  },
  {
    id: 3,
    TeamName: " Design",
    // Roles: "UX/UI Designers, Interaction Designers, Visual Designers, Graphic Designers ",
    Names: [
      "Cattleya Visanvit",
      "Ellen Beatty",
      "Happy Emerame",
      "Jiani Chen",
      "Kyle Welsh",
      "Mariam Abdulkareem",
      "Mary Dolmat",
      "Oluwafemi Adegbola Nurudeen",
    ],
  },
  {
    id: 4,
    TeamName: "Development",
    // Roles: " Software Engineers, Full-Stack Developers,Backend Developers,Frontend Developers, DevOps Engineers,Mobile App Developers ",
    Names: [
      "Amal Engulatov",
      "Abhirup Acharya",
      "Bauket Fabrice",
      "David Tevzadze",
      "Faizan Elahi",
      "Miguel Negron Garcia",
      "Nisha Fazululakhan",
      "Saad Elmesaoudi",
      "Oladimeji Stephen Ibitoye",
      "Sauhard Aggarwal",
      "Siddhant Ravindra Wadaskar",
      "Temitope Alabi",
      "Tyler Mason",
      "Yunus Olgan",
    ],
  },
  {
    id: 5,
    TeamName: "Financial Management  ",
    // Roles: "Financial Specialists, Financial Analysts  ",
    Names: ["Matías Berisso"],
  },
  {
    id: 6,
    TeamName: " Human Resources",
    // Roles: "HR Managers, HR Generalists, Talent Acquisition Specialists",
    Names: ["Grace Godwin"],
  },
  {
    id: 7,
    TeamName: " Legal and Compliance",
    // Roles: "General Counsel, Compliance Officer,Legal Counsel,Regulatory Affairs  Manager,Risk and Compliance Analyst,Privacy Officer, Ethics Officer, Contract Manager,Intellectual Property (IP) Manager,Compliance Training Specialist  ",
    Names: ["Dalia Hechi"],
  },
  {
    id: 8,
    TeamName: "Marketing and Public Relations ",
    // Roles: "Marketing Managers,PR Specialists, Communications Managers  ",
    Names: ["Abigail Ogbe", "Sean Banks"],
  },
  {
    id: 9,
    TeamName: "Product Management",
    // Roles: "Product Managers, Product Owners  ",
    Names: [
      "Ashley Garcia",
      "Genesis Cardenas",
      "Hsuan Ouyang",
      "Ines Ben Hassine",
      "Kathleen Davis",
      "Maiyi Huang",
      "Natsayi Nembaware",
    ],
  },
  {
    id: 10,
    TeamName: "Project Management ",
    // Roles: "Project Managers, Scrum Masters, Agile Coaches  ",
    Names: [
      "Anu Ramabhadran",
      "Folake Fadare",
      "Hana Javurkova",
      "Olamide Oseni",
      "Satyam Kishore",    
    ],
  },
  {
    id: 11,
    TeamName: "Quality Assurance ",
    // Roles: "QA Engineers, Testers, Quality Assurance Specialists  ",
    Names: [
      "Anastasiia Tkachuk",
      "Anthony Uyah",
      "Bhavitha Keezhuridathil",
      "Femi Gideon",
    ],
  },
  {
    id: 12,
    TeamName: "Research and Innovation ",
    // Roles: " Research Scientists, Innovation Strategists, R&D Specialists ",
    Names: ["Marcella Sarti Souza, MD"],
  },
  {
    id: 13,
    TeamName: "Social Media ",
    // Roles: " Social Media Managers, Social Media Specialists, Community Managers ",
    Names: ["Catherine Falardeau", "Molly Burke"],
  },
];

export default DataPage;