const DataPage = [
  //{
  // id: 1,
  // TeamName: "Copywriting",
  //  Roles: "Content Writers, Copywriters, Technical Writers",
  // Names: [""],
  //},

  {
    id: 1,
    TeamName: "Cybersecurity and Data Privacy",
    // Roles: "Cybersecurity,Privacy,Data Privacy ",
    Names: ["Somya Narain", "Viswajit Srinivasan"],
  },
  {
    id: 2,
    TeamName: "Data Science ",
    // Roles: "Data Analysts,Data Scientists,Data Engineers ",
    Names: [
      "Ayushi Malaviya",
      "Ebunoluwa Adejayan",
      "Onidajo Wale-Olayitan",
      "Pranav Vijayananth",
      "Rishitha Golla",
    ],
  },
  {
    id: 3,
    TeamName: " Design",
    // Roles: "UX/UI Designers, Interaction Designers, Visual Designers, Graphic Designers ",
    Names: [
      "Cattleya Visanvit",
      "Happy Emerame",
      "Kanchan Majithia",
      "Kyle Welsh",
      "Oluwafemi Nurudeen",
      "Priyadharshini Mohanlal",
      "Sweta Sinha",
      "Valerie Bui",
    ],
  },
  {
    id: 4,
    TeamName: "Development",
    // Roles: " Software Engineers, Full-Stack Developers,Backend Developers,Frontend Developers, DevOps Engineers,Mobile App Developers ",
    Names: [
      "Amal Engulatov",
      "Abhirup Acharya",
      "Archana Nitturi",
      "Bauket Fabrice",
      "Brian Burroughs",
      "Chris Cortese",
      "Chinmay Shringi",
      "David Tevzadze",
      "Faizan Elahi",
      "Gabriel Xavier",
      "John H. Carmona",
      "Jhansisridevi Mariappan",
      "Sanjivan Kumar",
      "Oladimeji Stephen Ibitoye",
      "Pahul Sidhu",
      "Temitope Alabi",
      "Ting Ting lin",
      "Tracy Li",
      "Tyler Mason",
    ],
  },
  {
    id: 5,
    TeamName: "Financial Management  ",
    // Roles: "Financial Specialists, Financial Analysts  ",
    Names: ["Matías Berisso"],
  },
  {
    id: 6,
    TeamName: " Human Resources",
    // Roles: "HR Managers, HR Generalists, Talent Acquisition Specialists",
    Names: ["Suchita Khandelwal"],
  },
  {
    id: 7,
    TeamName: " Legal and Compliance",
    // Roles: "General Counsel, Compliance Officer,Legal Counsel,Regulatory Affairs  Manager,Risk and Compliance Analyst,Privacy Officer, Ethics Officer, Contract Manager,Intellectual Property (IP) Manager,Compliance Training Specialist  ",
    Names: ["Dalia Hechi"],
  },
  {
    id: 8,
    TeamName: "Marketing and Public Relations ",
    // Roles: "Marketing Managers,PR Specialists, Communications Managers  ",
    Names: ["Rajandeep Dhariwal", "Shobana Rajendran"],
  },
  {
    id: 9,
    TeamName: "Product Management",
    // Roles: "Product Managers, Product Owners  ",
    Names: ["Hsuan Ouyang", "John Rucibigango"],
  },
  {
    id: 10,
    TeamName: "Project Management ",
    // Roles: "Project Managers, Scrum Masters, Agile Coaches  ",
    Names: [
      "Anu Ramabhadran",
      "Catherine Falardeau",
      "Folake Fadare",
      "Hana Javurkova",
      "Ishmeet Gill",
      "Pragya Sinha",
      "Satyam Kishore",
    ],
  },
  {
    id: 11,
    TeamName: "Quality Assurance ",
    // Roles: "QA Engineers, Testers, Quality Assurance Specialists  ",
    Names: ["Amjad Shahzad", "Anthony Uyah"],
  },
  {
    id: 12,
    TeamName: "Research and Innovation ",
    // Roles: " Research Scientists, Innovation Strategists, R&D Specialists ",
    Names: ["Marcella Sarti Souza, MD"],
  },
  {
    id: 13,
    TeamName: "Social Media ",
    // Roles: " Social Media Managers, Social Media Specialists, Community Managers ",
    Names: ["Shobana Rajendran"],
  },
];

export default DataPage;
