const DataPage = [
  // {
  //     id: 1,
  //     TeamName: "Copywriting",
  //     // Roles: "Content Writers, Copywriters, Technical Writers",
  //     Names: ["Emelie Enemo"],

  // },
  {
    id: 1,
    TeamName: "Cybersecurity and Data Privacy",
    // Roles: "Cybersecurity,Privacy,Data Privacy ",
    Names: ["Somya Narain", "Suchit Iyer", "Viswajit Srinivasan"],
  },
  {
    id: 2,
    TeamName: "Data Science ",
    // Roles: "Data Analysts,Data Scientists,Data Engineers ",
    Names: [
      // " Alim Nuriiev",
      "Amuche Ogugua",
      "Ayushi Malaviya",
      // "Audrey Gil",
      "Ebunoluwa Adejayan",
      // "Ellen Fernandez",
      // "Emmanuel Momoh",
      // "George Mendez",
      "Rishitha Golla",
      "Sourav Nanda",
    ],
  },
  {
    id: 3,
    TeamName: " Design",
    // Roles: "UX/UI Designers, Interaction Designers, Visual Designers, Graphic Designers ",
    Names: [
      // " Adel Akhmed",
      // "Anna Kholyavko",
      "Ellen Beatty",
      "Happy Emerame",
      // "Innocent Opara",
      "Jiani Chen",
      "Joy Li",
      "Mariam Abdulkareem",
      "Mary Dolmat",
      // "Nihan Kucukos",
      "Olawafemi Nurudeen",
      // "William Vo",
      "Yingying Huang",
    ],
  },
  {
    id: 4,
    TeamName: "Development",
    // Roles: " Software Engineers, Full-Stack Developers,Backend Developers,Frontend Developers, DevOps Engineers,Mobile App Developers ",
    Names: [
      "Abdulbasit Alabi",
      "Amal Engulatov",
      "Babalola Marvellous",
      "Barisanem Fiiwe",
      "Bauket Fabrice",
      "Cem Mehmet Onal",
      "Dennis Shaba",
      "Emmanuel Adewoye",
      "Enes Eken",
      "EPhrem Bayru",
      "George Karani",
      // "Imesh Chandrasiri",
      // "Kelvin Njuiri",
      // "Kiran Yadav",
      // "Krsna Patel",
      "Mark Owolo",
      "Nisha Fazululakha",
      "Oladimeji Ibitoye",
      "Oluwaferanmi Ogunrinola",
      "Soyeon Park",
      // "Udemeobong Akpan",
      "Valentine Wanjala Mukhebi",
      "Vedhapriya Rajagopal",
      // "Xuelan Wu",
      "Yunus Olgan",
    ],
  },
  {
    id: 5,
    TeamName: "Financial Management  ",
    // Roles: "Financial Specialists, Financial Analysts  ",
    Names: [" Matías Berisso", "Mulhoteni Gomani"],
  },
  {
    id: 6,
    TeamName: " Human Resources",
    // Roles: "HR Managers, HR Generalists, Talent Acquisition Specialists",

    // Names: ["Lucia Valerio", "Marissa Flanagan"],
    Names: [
      // " Aakriti Maharjan",
      "Grace Godwin",
      // "Marissa Flanagan",
      // "Sherrie Ricks",
    ],
  },
  {
    id: 7,
    TeamName: " Legal and Compliance",
    // Roles: "General Counsel, Compliance Officer,Legal Counsel,Regulatory Affairs  Manager,Risk and Compliance Analyst,Privacy Officer, Ethics Officer, Contract Manager,Intellectual Property (IP) Manager,Compliance Training Specialist  ",
    Names: ["Dalia Hechi"],
  },
  {
    id: 8,
    TeamName: "Marketing and Public Relations ",
    // Roles: "Marketing Managers,PR Specialists, Communications Managers  ",
    Names: [" Abigail Ogbe", "Sean Banks", "Xiaohan Ma"],
  },
  {
    id: 9,
    TeamName: "Product Management",
    // Roles: "Product Managers, Product Owners  ",
    Names: [
      // " Anjali Hill",
      "Ashley Garcia",
      "Genesis Cardenas",
      "Hsuan Ouyang",
      "Kathleen Davis",
      "Lane McCoy",
      "Maiyi Huang",
      "Natsayi Nembaware",
      // "Susan Haynes",
    ],
  },
  {
    id: 10,
    TeamName: "Project Management ",
    // Roles: "Project Managers, Scrum Masters, Agile Coaches  ",
    Names: [
      "Anu Ramabhadran",
      "Folake Fadare",
      // "Frank Saladis, PMP",
      "Hana Javurkova",
      "Keziah Kam",
      "Satyam Kishore",
    ],
  },
  {
    id: 11,
    TeamName: "Quality Assurance ",
    // Roles: "QA Engineers, Testers, Quality Assurance Specialists  ",
    Names: [
      // "Atharva Bhadke",
      "Anastasiia Tkachuk",
      "Bhavitha Keezhuridathil",
      "Femi Gideon",
      "Imran Choudhury",
      "Piyush Chakkarwar",
      // "Vikram Bhanapur",
    ],
  },
  {
    id: 12,
    TeamName: "Research and Innovation ",
    // Roles: " Research Scientists, Innovation Strategists, R&D Specialists ",
    Names: ["Marcella Souza, MD"],
  },
];

export default DataPage;
