const DataPage = [
  {
    id: 1,
    TeamName: "Administration",
    // Roles: "HR, Recruiting, Research, Events",
    Names: [
      // "Celia Arrecis ",
      "Ebunoluwa Adebimpe",
      "Precious llenre",
      "Precious Nkeiruka Uzoma",
      "Priscillah Gichure",
    ],
  },
  {
    id: 2,
    TeamName: "Copywriting",
    // Roles: "Content Writers, Copywriters, Technical Writers",
    Names: ["Kythera Contreras"],
  },

  {
    id: 3,
    TeamName: "Cybersecurity and Data Privacy",
    // Roles: "Cybersecurity,Privacy,Data Privacy ",
    Names: [, "Viswajit Srinivasan"],
  },
  {
    id: 4,
    TeamName: "Data Analysis",
    // Roles: "Data Analysts, Clinical Trials",
    Names: [
      "Adam Albaghali",
      // "Adelina Rama",
      "Chukwuemeka Francis",
      "Ebunoluwa Adejayan",
      "Habeeb Sulaimon",
      "Job Sidney",
      "Prit Italiya",
      "Yashdeep Raulji",
    ],
  },
  {
    id: 5,
    TeamName: "Design",
    // Roles: "UX/UI Designers, Interaction Designers, Visual Designers, Graphic Designers",
    Names: [
      // "Anna Chevalier",
      "Elisa D",
      "Derrick Ugiagbe",
      // "Happy Emerame",
      "Quinn Devlin",
      "Ronald Anthony",
      // "Tatiana Golitsyna",
      "Tetiana Zabolotna",
      "Wilson Barrios",
    ],
  },
  {
    id: 6,
    TeamName: "Engineers",
    // Roles: "Software Engineers, Full-Stack Developers, Backend Developers, Frontend Developers, DevOps Engineers, Mobile App Developers",
    Names: [
      // "Adegoke Bestman",
      "Alfred Ayi-Bonte",
      "Amal Engulatov",
      "Aman Goel",
      "Ayodele John",
      "Bauket Fabrice",
      // "David Walton",
      "Emmanuella Agubuzo",
      "Fawaz Bailey",
      "Isacc Wren",
      "Joe Gallagher",
      // "Josue Abraham Cabrales Ramirez",
      "Kevin Fluth",
      "Prenav Sathianathan",
      "Ojasvi Jagtap",
      "Oladimeji Stephen Ibitoye",
      "Olaolu Adigun",
      "Padmini Katekar",
      "Poojan Dhaduk",
      "Ritesh Rawal",
      "Ritu Goyal",
      "Rodrigo Cipriano",
      "Salmon Gowa",
      "Samuel Kingsford Amoah",
      // "Stanley Samuel Arikpo",
      "Sahil Nitinbhai Bhuva",
      "Simarjeet Kaur",
      "Wenjie Werder",
    ],
  },
  {
    id: 7,
    TeamName: "Financial Management",
    // Roles: "Financial Specialists, Financial Analysts",
    Names: [
      "Ayebapreye Kari",
      "Isabel Friedenzohn",
      "Jimmy Fraggos",
      // "Keairra A. Adams",
      "Kwena Lovedonia Moyaha",
      "Matías Berisso",
    ],
  },
  {
    id: 8,
    TeamName: "Human Resources",
    // Roles: "HR Managers, HR Generalists, Talent Acquisition Specialists",
    Names: [
      "Eliza Fiedler",
      "Srushti Chaudhari",
      "Swetha Guda",
      "Sylvia Ezechie",
    ],
  },
  // {
  //   id: 9,
  //   TeamName: "Legal and Compliance",
  //   // Roles: "General Counsel, Compliance Officer, Legal Counsel, Regulatory Affairs Manager, Risk and Compliance Analyst, Privacy Officer, Ethics Officer, Contract Manager, Intellectual Property (IP) Manager, Compliance Training Specialist",
  //   Names: ["Dalia Hechi"],
  // },
  {
    id: 10,
    TeamName: "Marketing and Public Relations",
    // Roles: "Marketing Managers, PR Specialists, Communications Managers",
    Names: [
      // "Lipi Chaudhari",
      "Richard Kamau",
      "Samson Kayode Tuwa",
    ],
  },
  {
    id: 11,
    TeamName: "Product Management",
    // Roles: "Product Managers, Product Owners",
    Names: ["Amudha Ekambaram", "Hsuan Ouyang", "Ify Oshilim"],
  },
  {
    id: 12,
    TeamName: "Project Management",
    // Roles: "Project Managers, Scrum Masters, Agile Coaches",
    Names: [
      "Catherine Falardeau",
      "Douha Madkour",
      "Hana Javurkova",
      "Joseph Osei-Kusi",
      "Nekeshia Henderson Hartman",
      "Radhika Kulkarni",
      "Sabiki llesanmi",
      "Sirisha Vundavalli",
      "Srujana Kethamukkala",
      "Sylvia Ezechie",
    ],
  },
  {
    id: 13,
    TeamName: "Quality Assurance",
    // Roles: "QA Engineers, Testers, Quality Assurance Specialists",
    Names: [
      "Adithya Arun",
      "Adrian Chiriac",
      "Deepa Dhoke",
      "Derrick Owusu Ansah",
      "Isacc Wren",
      "Kishore Kulkarni",
      "Olga Chirkova",
      "Priyanka Patil",
      "Prosper Chidiegwu Amutah",
      "Sarika Naphade",
      "Vershima Kelvin Ityavyar",
    ],
  },
  {
    id: 14,
    TeamName: "Research and Innovation",
    // Roles: "Research Scientists, Innovation Strategists, R&D Specialists",
    Names: ["Isaac Oommen", "Marcella Sarti Souza, MD"],
  },
  {
    id: 15,
    TeamName: "Social Media",
    //  Roles: "Social Media Managers, Social Media Specialists, Community Managers",
    Names: [
      "Nwoke Oluebube Chioma",
      //  "Satyam Kishore",
      "Uche Agholor",
    ],
  },
];

export default DataPage;