const DataPage = [
  {
    id: 1,
    TeamName: "Administration",
    // Roles: "HR, Recruiting, Research, Events",
    Names: [
      // "Celia Arrecis ",
      "Anthonia Ovie",
      "Ebunoluwa Adebimpe",
      "Eunice Benu",
      "Precious llenre",
      "Precious Nkeiruka Uzoma",
      // "Priscillah Gichure",
    ],
  },
  {
    id: 2,
    TeamName: "Copywriting",
    // Roles: "Content Writers, Copywriters, Technical Writers",
    Names: ["Jeffrey Lunnie"],
  },

  {
    id: 3,
    TeamName: "Cybersecurity and Data Privacy",
    // Roles: "Cybersecurity,Privacy,Data Privacy ",
    Names: [, "Viswajit Srinivasan"],
  },
  {
    id: 4,
    TeamName: "Data Analysis",
    // Roles: "Data Analysts, Clinical Trials",
    Names: [
      "Abhay Kumar",
      "Adam Albaghali",
      "Bilyaminu Ibrahim",
      // "Adelina Rama",
      "Chukwuemeka Francis",
      "Ebunoluwa Adejayan",
      "Habeeb Sulaimon",
      "Job Sidney",
      "Prit Italiya",
      "Temidayo Olowoyeye",
      // "Yashdeep Raulji",
    ],
  },
  {
    id: 5,
    TeamName: "Design",
    // Roles: "UX/UI Designers, Interaction Designers, Visual Designers, Graphic Designers",
    Names: [
      "Akindele Oluwadunsin",
      // "Anna Chevalier",
      "Derrick Ugiagbe",
      "Dominic Zambrano",
      "Efemena Hilda",
      // "Iswarya krishna",
      "Esther Onoruke",
      "Paris Roman",
      "Iswarya Krishna",
      "Jashwanth Polemoni",
      "Jermaine Brown",
      "Joseph Rienzo",
      "Juile Cornell",
      "marcela Aristizabal-Julio",
      // "Noopur Shah",
      "Oluwakayode Opeyemi",
      "Paul Nguyen",
      // "Happy Emerame",
      // "Quinn Devlin",
      "Ronald Anthony",
      "Shadrach Godwin",
      "Suja Mariadoss",
      "Tatiana Golitsyna",
      "Tianfang Si",
      "Zalihat Mohammed",
      // "Tetiana Zabolotna",

      // "Wilson Barrios",
    ],
  },
  {
    id: 6,
    TeamName: "Engineers",
    // Roles: "Software Engineers, Full-Stack Developers, Backend Developers, Frontend Developers, DevOps Engineers, Mobile App Developers",
    Names: [
      // "Adegoke Bestman",
      // "Aarif Elkhatib",
      // "Agbenyo Samuel",
      "Alfred Ayi-Bonte",
      "alli Hasnain",
      // "Amal Engulatov",
      // "Ammar Yasser Mohamed",
      "Aman Goel",
      "Ammar Yasser Mohammed",
      "Ayodele John",
      "Brian Clements-Tiberio",
      "Egbetayo Damilola",
      "Edidiong Akpanowo",
      "Ekine Chukwuemeka Emmanuel",
      // "Bauket Fabrice",
      // "David Walton",
      // "Emmanuella Agubuzo",
      // "Elisa D",
      "Fawaz Bailey",
      "Gabriel Oyinola",
      "Godswill Akpa",
      "Idorenyin Williams",
      "Isacc Wren",
      // "Inzamam Akram",
      "James Samchez",
      // "Jane Thwaite",
      "Jeramia Adewara Inioluwa",
      "Jeremy Griffin",
      // "Joe Gallagher",
      // "Josue Abraham Cabrales Ramirez",
      "Kaviya Rajendran",
      "keerthana Kuruganti",
      // "Kevin Fluth",
      "Laura Vargas Gomez",
      "Logan Crouch",
      // "Maamar Haddouche",
      // "Kohinoor Lewis",
      "Micheal Ene Henry",
      "Muhammed Ali",
      // "Mike Seabrook",
      "Nanditha ArunaChalam",

      // "Neha Shan",
      "Nkaze Andreson",
      "Obiajulu Anthony",
      "Ojasvi Jagtap",
      "Oladimeji Stephen Ibitoye",
      // "Olaolu Adigun",
      // "Padmini Katekar",
      "Oludayo Orunsolu",
      // "Prenav Sathianathan",

      // "Poojan Dhaduk",
      // "Ritesh Rawal",
      "Ritu Goyal",
      // "Rodrigo Cipriano",
      // "Salmon Gowa",
      "Samuel Kingsford Amoah",
      // "Stanley Samuel Arikpo",
      // "Sahil Nitinbhai Bhuva",
      "Shepherd Praise Onoja",
      "Steven Andrew",
      "Tyler Lopez",
      "Venkata Narayana",
      "Xijing Zhang",
      "Zachary Alan Speer",
      // "Simarjeet Kaur",
      // "Wenjie Werder",
    ],
  },
  {
    id: 7,
    TeamName: "Financial Management",
    // Roles: "Financial Specialists, Financial Analysts",
    Names: [
      "Ayebapreye Kari",
      // "Isabel Friedenzohn",
      "Jimmy Fraggos",
      // "Keairra A. Adams",
      "Kwena Lovedonia Moyaha",
      "Peter Wani Kanisio",
      "Matías Berisso",
    ],
  },
  {
    id: 8,
    TeamName: "Human Resources",
    // Roles: "HR Managers, HR Generalists, Talent Acquisition Specialists",
    Names: [
      // "Eliza Fiedler",
      "Anna Palkina",
      "Srushti Chaudhari",
      "Swetha Guda",
      "Sylvia Ezechie",
    ],
  },
  // {
  //   id: 9,
  //   TeamName: "Legal and Compliance",
  //   // Roles: "General Counsel, Compliance Officer, Legal Counsel, Regulatory Affairs Manager, Risk and Compliance Analyst, Privacy Officer, Ethics Officer, Contract Manager, Intellectual Property (IP) Manager, Compliance Training Specialist",
  //   Names: ["Dalia Hechi"],
  // },
  {
    id: 10,
    TeamName: "Marketing and Public Relations",
    // Roles: "Marketing Managers, PR Specialists, Communications Managers",
    Names: [
      // "Lipi Chaudhari",
      "Andy Gallegos",
      "Mary Ojebode",
      "Richard Kamau",
      "Samson Kayode Tuwa",
      "Starlyn Robinson",
    ],
  },
  {
    id: 11,
    TeamName: "Product Management",
    // Roles: "Product Managers, Product Owners",
    Names: [
      "Aarti Seshadri",
      "Aarya Sharma",
      "Amudha Ekambaram",
      "Cynthia Esperanza",
      // "Gbemisola Akerele",
      "Hsuan Ouyang",
      "Ify Oshilim",
      "Jaimin Patel",
      "Kenneth Faulks",
      "marjorie Lamour",
    ],
  },
  {
    id: 12,
    TeamName: "Project Management",
    // Roles: "Project Managers, Scrum Masters, Agile Coaches",
    Names: [
      "Adhithya Rajasekaran",
      "Catherine Falardeau",
      // "Douha Madkour",
      "Hana Javurkova",
      "Joseph Kofi Boakye",
      "Joseph Osei-Kusi",
      "Nekeshia Henderson Hartman",
      "Radhika Kulkarni",
      "Sabiki llesanmi",
      "Sarah Castillo",
      "Sirisha Vundavalli",
      "Srujana Kethamukkala",
      "Sylvia Ezechie",
    ],
  },
  {
    id: 13,
    TeamName: "Quality Assurance",
    // Roles: "QA Engineers, Testers, Quality Assurance Specialists",
    Names: [
      "Adithya Arun",
      "Adrian Chiriac",
      // "Deepa Dhoke",
      "Derrick Owusu Ansah",
      // "Isacc Wren",
      // "Kishore Kulkarni",
      "Madhuri Chavali",
      "Olga Chirkova",
      "Pramada Reddy",
      "Priyanka Patil",
      "Prosper Chidiegwu Amutah",
      // "Sarika Naphade",
      // "Venkata Jaganath Wunnava",
      "Vershima Kelvin Ityavyar",
    ],
  },
  {
    id: 14,
    TeamName: "Research and Innovation",
    // Roles: "Research Scientists, Innovation Strategists, R&D Specialists",
    Names: ["Isaac Oommen", "Marcella Sarti Souza, MD"],
  },
  {
    id: 15,
    TeamName: "Social Media",
    //  Roles: "Social Media Managers, Social Media Specialists, Community Managers",
    Names: [
      "Nwoke Oluebube Chioma",
      //  "Satyam Kishore",
      "Uche Agholor",
    ],
  },
];

export default DataPage;
