const DataPage = [
  // {
  // id: 1,
  // TeamName: "Copywriting",
  // Roles: "Content Writers, Copywriters, Technical Writers",
  // Names: [""],
  // },

  {
    id: 1,
    TeamName: "Administration",
    // Roles: "HR, Recruiting, Research, Events",
    Names: [
      "Celia Arrecis ",
      "Ebunoluwa Adebimpe",
      "Precious llenre",
      "Precious Nkeiruka Uzoma",
      "Priscillah Gichure",
    ],
  },
  {
    id: 2,
    TeamName: "Cybersecurity and Data Privacy",
    // Roles: "Cybersecurity,Privacy,Data Privacy ",
    Names: [, "Viswajit Srinivasan"],
  },
  {
    id: 3,
    TeamName: "Data Analysis",
    // Roles: "Data Analysts, Clinical Trials",
    Names: [
      "Adam Albaghali",
      "Adelina Rama",
      "Chukwuemeka Francis",
      "Ebunoluwa Adejayan",
      "Habeeb Sulaimon",
      "Job Sidney",
      "Prit Italiya",
      "Yashdeep Raulji",
    ],
  },
  {
    id: 4,
    TeamName: "Design",
    // Roles: "UX/UI Designers, Interaction Designers, Visual Designers, Graphic Designers",
    Names: [
      // "Anna Chevalier",
      "Derrick Ugiagbe",
      "Happy Emerame",
      "Quinn Devlin",
      "Tatiana Golitsyna",
      "Tetiana Zabolotna",
      "Wilson Barrios",
    ],
  },
  {
    id: 5,
    TeamName: "Engineers",
    // Roles: "Software Engineers, Full-Stack Developers, Backend Developers, Frontend Developers, DevOps Engineers, Mobile App Developers",
    Names: [
      "Adegoke Bestman",
      "Alfred Ayi-Bonte",
      "Amal Engulatov",
      "Aman Goel",
      "Bauket Fabrice",
      "David Walton",
      "Emmanuella Agubuzo",
      "Fawaz Bailey",
      "Isacc Wren",
      "Joe Gallagher",
      "Josue Abraham Cabrales Ramirez",
      "Kevin Fluth",
      "Oladimeji Stephen Ibitoye",
      "Olaolu Adigun",
      "Padmini Katekar",
      "Poojan Dhaduk",
      "Ritesh Rawal",
      "Ritu Goyal",
      "Rodrigo Cipriano",
      "Salmon Gowa",
      "Samuel Kingsford Amoah",
      "Stanley Samuel Arikpo",
    ],
  },
  {
    id: 6,
    TeamName: "Financial Management",
    // Roles: "Financial Specialists, Financial Analysts",
    Names: [
      "Ayebapreye Kari",
      "Jimmy Fraggos",
      "Keairra A. Adams",
      "Kwena Lovedonia Moyaha",
      "Matías Berisso",
    ],
  },
  {
    id: 7,
    TeamName: "Human Resources",
    // Roles: "HR Managers, HR Generalists, Talent Acquisition Specialists",
    Names: [
      "Eliza Fiedler",
      "Srushti Chaudhari",
      "Swetha Guda",
      "Sylvia Ezechie",
    ],
  },
  {
    id: 8,
    TeamName: "Legal and Compliance",
    // Roles: "General Counsel, Compliance Officer, Legal Counsel, Regulatory Affairs Manager, Risk and Compliance Analyst, Privacy Officer, Ethics Officer, Contract Manager, Intellectual Property (IP) Manager, Compliance Training Specialist",
    Names: ["Dalia Hechi"],
  },
  {
    id: 9,
    TeamName: "Marketing and Public Relations",
    // Roles: "Marketing Managers, PR Specialists, Communications Managers",
    Names: [
      // "Lipi Chaudhari",
      "Richard Kamau",
      "Samson Kayode Tuwa",
    ],
  },
  {
    id: 10,
    TeamName: "Product Management",
    // Roles: "Product Managers, Product Owners",
    Names: ["Amudha Ekambaram", "Hsuan Ouyang", "Ify Oshilim"],
  },
  {
    id: 11,
    TeamName: "Project Management",
    // Roles: "Project Managers, Scrum Masters, Agile Coaches",
    Names: [
      "Catherine Falardeau",
      "Douha Madkour",
      "Hana Javurkova",
      "Joseph Osei-Kusi",
      "Nekeshia Henderson Hartman",
      "Radhika Kulkarni",
      "Sabiki llesanmi",
      "Sirisha Vundavalli",
      "Srujana Kethamukkala",
      "Sylvia Ezechie",
    ],
  },
  {
    id: 12,
    TeamName: "Quality Assurance",
    // Roles: "QA Engineers, Testers, Quality Assurance Specialists",
    Names: [
      "Adithya Arun",
      "Adrian Chiriac",
      "Deepa Dhoke",
      "Derrick Owusu Ansah",
      "Isacc Wren",
      "Kishore Kulkarni",
      "Olga Chirkova",
      "Priyanka Patil",
      "Prosper Chidiegwu Amutah",
      "Sarika Naphade",
      "Vershima Kelvin Ityavyar",
    ],
  },
  {
    id: 13,
    TeamName: "Research and Innovation",
    // Roles: "Research Scientists, Innovation Strategists, R&D Specialists",
    Names: ["Isaac Oommen", "Marcella Sarti Souza, MD"],
  },
  {
    id: 14,
    TeamName: "Social Media",
    //  Roles: "Social Media Managers, Social Media Specialists, Community Managers",
    Names: ["Nwoke Oluebube Chioma", "Satyam Kishore", "Uche Agholor"],
  },
];

export default DataPage;